In [16]:
import numpy
import os
import time
import random
import numpy as np

In [ ]:
# Define a couple of variabiles
a = 3 # this is an "int"
b = 2.1 # this is a "float"
s = "Hello, World!" # this is a "str"
c = True # this is a "bool"

print(type(a))
print(type(s))

In [4]:
pi = 3.1415729327329032
print(f"the value of pi is: {pi:0.4f}")

the value of pi is: 3.1416


In [ ]:
# Create a tuple
t = (1, True, "Hello")
print(t)
print(type(t))
# Tuple are not dinamic, are immutable
# t[0] = 2 ERROR

# And a List
# List can have different types
l = [2.3, 1, 0, -2]
print(l)
print(type(l))
print(type(l[0]), type(l[1]))

(1, True, 'Hello')
<class 'tuple'>
[2.3, 1, 0, -2]
<class 'list'>
<class 'float'> <class 'int'>


In [9]:
# Define a path (possibly relative to the current Working Directory)
path = "./"

# Print the files in the given path
print(os.listdir(path))


['.git', '.ipynb_checkpoints', 'data', 'lessons-1.ipynb', 'README.md']


In [14]:
# Initialize a random array of length 100_000
l = [random.gauss() for _ in range(100_000)]

# Start timer
start_time = time.time()

# Cycle on l and project to 0 all the negative elements
for i in range(len(l)):
    if l[i] < 0:
        l[i] = 0

# End timer
end_time = time.time()

# Print execution time
print(end_time - start_time)

0.01627802848815918


In [17]:
# Define a Python list
a = [1, 2, 3]

# Convert it to numpy array
a_vec = np.array(a)

# Check the type of a_vec
print(type(a_vec))

<class 'numpy.ndarray'>


In [21]:
A = [[1, 1, -1], [2, 0, 0], [0, 1, 2]]
A = np.array(A)
print(A)
print(A.shape) # Use .shape to print the shape

[[ 1  1 -1]
 [ 2  0  0]
 [ 0  1  2]]
(3, 3)


In [25]:
v = np.array([1,2,3]) #one dimensional vecotor or abstract vector
print(v.shape)
w = np.array([[1,2,3]]) #row vectors
print(w.shape)
x = np.array([[1],[2],[3]]) # column vectors
print(x.shape)

(3,)
(1, 3)
(3, 1)


In [28]:
# Element for element operations
# it happen for: +, -, /, *, **

v = np.array([1,0,-1])
w = np.array([-1,1,2])

# to perform dot product:
print(v@w) # siccome sono entrambi a dimensionali fa finta che il primo sia una riga ed il secondo una colonna
print(np.dot(v,w))
print(np.inner(v,w))
print(v.dot(w))

-3
-3
-3
-3
