In [5]:
import numpy as np

# Define a Python list
a = [1, 2, 3]

# Convert it to numpy array
a_vec = np.array(a)

# Check the type of a_vec
print(type(a_vec))
print(a_vec.shape)
print(a_vec.T.shape)

<class 'numpy.ndarray'>
(3,)
(3,)


In [11]:
w = np.linspace(1, 5, 5)
print(w)
w = np.arange(1, 10, 2)
print(w)

[1. 2. 3. 4. 5.]
[1 3 5 7 9]


In [15]:
w = np.zeros((5, 5))
print(w)
w = np.zeros((5, ))
print(w)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
